### ISSUE TITLE
build-status check error 'file not found'

### ISSUE THREAD

**Issue by vorotech** [SHyx0rmZ/bitbucket-build-status-resource#6]
Hello,
I'd like to report an issue which I continuously receive when restart local concourse set up with docker-compose. Unfortunately it is not recoverable (at least I didn't find the way), so the only workaround is to set-pipeline from scratch.

How it looks in Concourse 4.0.0
![image](https://user-images.githubusercontent.com/2937451/45594228-cae8e780-b99f-11e8-9278-a0a4d930d9ec.png)

The error from the log

```
concourse-web_1     | {"timestamp":"1537084382.970843792","source":"atc","message":"atc.syncer.foundation-ci:radar.scan-resource.interval-runner.tick.failed-to-initialize-new-container","log_level":2,"data":{"error":"file not found","pipeline-scoped-name":"foundation-ci:resource:build-status","session":"39.1.14.1.2"}}
```

Tbh, I'm not 100% sure it is related to this resource, but among all resources in my pipeline this one is only not recovering, after the stale workers are being pruned.

**Comment by vorotech** [comment]
My resource config:

```
- name: build-status
  type: bitbucket-build-status
  source:
    driver: Bitbucket Cloud
    repository: my/repo
    client_id: ((bitbucket-app-oauth-key))
    client_secret: ((bitbucket-app-oauth-secret))
```
